name: macos

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    if: ${{ (! endsWith(github.event.head_commit.message, '- android') && ! endsWith(github.event.head_commit.message, '- windows') && ! endsWith(github.event.head_commit.message, '- linux') && endsWith(github.event.head_commit.message, '- macos')) || true }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        include:
          - os: macos-latest
            name: macos

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.name }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: cmake build
        run: |
          make CC=clang CXX=clang++

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: program-windows.exe
      #     path: ./program-windows.exe
      #     retention-days: 1
