name: macos

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  should_run:
    runs-on: ubuntu-latest
    name: should_i_run
    outputs:
      output1: ${{ steps.check.outputs.target_commit_id }}
    steps:
     - name: check
       run: |
         wget https://gist.github.com/mgood7123/47957c59a4b0cbda11875632ee0b8f15/raw/02e6f9f5e30c7d06642b54bbf45534267bfad8a5/check.cpp -O check.cpp
         cat << EOF > json.cpp
         const char * json_data = R"(
             ${{toJSON(github.event.commits.*)}}
         )";
         EOF
         git clone https://github.com/danielaparker/jsoncons --depth=1
         g++ --std=c++17 -I jsoncons/include check.cpp json.cpp -o check
         ./check 4 >> "$GITHUB_OUTPUT" # check for android [1] windows [2] linux [3] macos [4]
  
  build:
    needs: should_run
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        include:
          - os: macos-latest
            name: macos

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.name }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: ${{needs.should_run.outputs.output1}}
          submodules: recursive

      - name: cmake build
        run: |
          make CC=clang CXX=clang++

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: program-windows.exe
      #     path: ./program-windows.exe
      #     retention-days: 1
