name: windows

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    shell: msys2 {0}

jobs:
  build:
    if: ${{ (! endsWith(github.event.head_commit.message, '- android') && endsWith(github.event.head_commit.message, '- windows') && ! endsWith(github.event.head_commit.message, '- linux') && ! endsWith(github.event.head_commit.message, '- macos')) || true }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows
            sys: clang64

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.name }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: '${{ matrix.icon }} Setup MSYS2'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          update: true

      - name: update packages
        run: |
          echo "github.event.head_commit.message = '${{github.event.head_commit.message}}'"
          pacman -Sy

      - name: install pacboy
        run: |
          pacman -Syu --noconfirm --needed pactoys

      - name: update packages
        run: |
          pacboy -Sy

      - name: install packages
        run: |
          pacboy -S --noconfirm --needed clang:p make:p cmake:p autotools:p

      - name: cmake build
        run: |
          mingw32-make CC=clang CXX=clang++ CMAKE_FLAGS="-DCMAKE_MAKE_PROGRAM=mingw32-make"

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: program-windows.exe
      #     path: ./program-windows.exe
      #     retention-days: 1
