name: windows

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: msys2 {0}

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows
            sys: clang64

    runs-on: ${{ matrix.os }}
    
    name: ${{ matrix.name }} - ${{ matrix.sys }}
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: '${{ matrix.icon }} Setup MSYS2'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          update: true

      - name: which pacman
        run: |
          which pacman

      - name: pacman help
        run: |
          pacman --help

      - name: clang help
        run: |
          clang --help

      - name: cmake build
        run: |
          make CC=clang CXX=clang++

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: program-windows.exe
      #     path: ./program-windows.exe
      #     retention-days: 1
